### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by tooomm**
Hope this is the right spot to fix this.

### CODE REVIEW

**Comment by ryecoaaron** [comment]
I almost think it should be "be fixed" instead of "get fixed".

**Comment by tooomm** [comment]
After reading it again, I agree! 👍

**Comment by tooomm** [comment]
I read [your comment in the forum](https://forum.openmediavault.org/index.php?thread/30045-flashmemory-plugin-for-omv-5-x/&postID=223379#post223379), which contained some very helpful information next to the rest of the discussion.
Shouldn't some of this basic information and explanation be part of the plugin page to let beginners know as well?

What do you think about the additional hints and clarification in https://github.com/tooomm/openmediavault-flashmemory/commit/3b60de1c5dc886a6a601a7612d1dff2f18853769?
Not exactly sure yet what the kB count refers to. Written kB to RAM? Written kB to flash drive?

I happily tweak it further and open a PR for discussing the exact wording.

I'm totally aware that this all might be obvious to the experienced user. But this little tweaks would have helped me for example.

**Comment by ryecoaaron** [comment]
I thought the plugin info was verbose enough.  If someone doesn't understand it and it said optional, I figured they would just skip it.  And that is fine to do.  If the instructions are too long, people don't read them.

Write Kbytes is the amount written to the disk that is the root filesystem since boot.  It is just meant to give a clue how much data is being written.  Since most usb sticks don't have a write lifetime, it doesn't help much.  I thought about removing it for years.

**Comment by tooomm** [comment]
For inexperienced omv/linux beginners, the instructions might not be clear enough. From a user point of view with limited pre-knowledge it's not ideal. (I am one of those new users with only some experience)

I totally see the good intention in removing e.g. the "enabled" switch and generally trying to design the plugin as minimal and automated as possible. But sometimes basic hints, which are not self explanatory for everybody, are left out in the process.
In this example, the flash memory plugin is basically the only extension which doesn't need to be enabled if I'm not mistaken. That's not intuitive and can be an unexpected experience for the user questioning the functionality. Normally the process of using a plugin is 1. install it and 2. enable + configure it. If that is different, the plugin should tell the user IMO. There might still be good reasons for doing this... but a simply little hint, that the plugin works out of the box would do the trick with no harm. Obvious for some - confusing for others.
I also think the plugin should speak for itself and shouldn't rely on other, external sources or too much preknowledge to explain it's workings.

Will think about some tweaks from my (inexperienced) point of view and let you know. Maybe I post a little mockup for the plugin page and you see fit. Too much text is also not great, agreed.

**Comment by ryecoaaron** [comment]
Since there is no configuration, I didn't think having an enable switch made sense.  It also made automating the install easier. And there are other plugins with no enable (snapraid comes to mind).  I think it is strange that a user would assume it needs to be enabled or even configured when there is no enable switch or fields to configure.  But I am terrible about understanding OMV noobs that only think about Windows.

The biggest issue with all of this is that most people don't need to get rid of swap and all of these issue are about getting rid of swap.  But if you can write instructions that noobs understand and I don't have to do it. fine with me.

As for external sources explaining a plugin's workings, most plugins don't explain their workings.  People may be familiar with them and don't need them but most do not explain more than just their settings.

**Pull request merged**
